from pathlib import Path

CURRENT='20261011-42'

# The shared module may have been patched to 41 immediately before this step.
module=Path('narrative-universe.js')
s=module.read_text(encoding='utf-8')
s=s.replace("const VERSION='20261011-41';", f"const VERSION='{CURRENT}';")
module.write_text(s,encoding='utf-8')

ana=Path('elegia-breve/index.html')
t=ana.read_text(encoding='utf-8')

# All links generated by the related-works index must point to the current route version.
for old in ('20261011-39','20261011-40','20261011-41'):
    t=t.replace(f'v={old}',f'v={CURRENT}')

# A stale index URL should immediately self-correct to the current version.
guard=f'''<script id="oras-index-version-guard">
(()=>{{
  const CURRENT='{CURRENT}';
  const u=new URL(location.href);
  if(u.searchParams.get('indice')==='1' && u.searchParams.get('v')!==CURRENT){{
    u.searchParams.set('v',CURRENT);
    location.replace(u.toString());
  }}
}})();
</script>'''
if 'id="oras-index-version-guard"' not in t:
    t=t.replace('</head>',guard+'\n</head>',1)

# Deployment must contain the two visual motifs and the question-only Ceniciento gate.
required=(
    'const soloArt=`',
    'rect x="0" y="0" width="70" height="48"',
    'const cenArt=`',
    'id="ashHair"',
    'cenicientoQuestionUnlocked',
)
missing=[item for item in required if item not in t]
if missing:
    raise RuntimeError('Faltan elementos del índice relacionado: '+', '.join(missing))

ana.write_text(t,encoding='utf-8')
print('PASS: related-work motifs, question gate and current index version are present')
