const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const page=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const mirror=fs.readFileSync(path.join(__dirname,'el-espejo.js'),'utf8');
const shared=fs.readFileSync(path.join(__dirname,'../narrative-universe.js'),'utf8');
const ana=fs.readFileSync(path.join(__dirname,'../elegia-breve/index.html'),'utf8');
assert.equal((mirror.match(/^`/gm)||[]).length,32,'EL ESPEJO contains exactly 32 scenes');
assert(mirror.includes('new Set([14,15,17,26,30])'),'Five convergence scenes pause for reader action');
assert(mirror.includes("next.textContent='seguir'")&&mirror.includes('if(!locked||lockedScene!==scene)return'),'The reader controls each key-scene pause');
assert(!/setTimeout|setInterval/.test(mirror.slice(0,mirror.indexOf('const endSentinel'))),'Scene pacing does not depend on timers');
assert(mirror.includes('if(event.deltaY<0){releasePause();return}')&&mirror.includes("['ArrowUp','PageUp','Home'].includes(event.key)"),'Readers can reread by moving back');
assert(mirror.includes("mark.textContent='flag'")&&mirror.indexOf("mark.textContent='flag'")<mirror.indexOf("end.className='mirror-end-sentinel'"),'The sole visible closing mark appears immediately before automatic return');
assert(page.includes('<main id="mirror" aria-label="EL ESPEJO" hidden></main>'),'The convergence remains hidden until its narrative condition');
assert(page.includes('data-oras-mirror="true" src="el-espejo.js?v=20261010-23"'),'The mirror script is registered for shared startup');
assert(shared.includes('state.anaComplete&&state.soloComplete&&state.cenicientoComplete&&state.cenicientoUnlocked&&!state.mirrorReadComplete'),'The convergence waits for all three complete first readings');
assert(shared.includes("completePiece('anaComplete')")&&shared.includes("completePiece('cenicientoComplete'")&&shared.includes('maybeStartMirror();'),'Every piece completion checks for the convergence, regardless of reading order');
assert(shared.includes("save({mirrorReadComplete:true,returnedFromCeniciento:true})"),'Finishing EL ESPEJO records completion and return');
assert(shared.includes("topGo(rootPath+'elegia-breve/?v='+VERSION)")&&shared.includes("type:'mirror-return'"),'EL ESPEJO returns automatically to the beginning of ANA KLAUDYA');
assert(ana.includes("data.type==='mirror-return'){returnToAna('home');return;}"),'The Ana host closes embedded Mirror and restores its opening');
assert(shared.includes("box.className='ou-reading-checklist'")&&shared.includes('data-piece="solo"><span>SOLO LA TARJETA</span>')&&shared.includes("row.setAttribute('aria-label'"),'A single compact accessible checklist tracks the three pieces');
assert(!page.includes('id="continue"')&&!page.includes('cont.onclick'),'Read and Voice have no second start button');
assert(page.includes("voice.play().then(loop)"),'Voice playback starts directly from the mode selection');
assert.equal((shared.match(/Hay historias que empiezan antes\.|El origen suele parecer insignificante\.|Falta una versión de la historia\.|Nadie regresa al mismo lugar\./g)||[]).length,4,'The four ghost phrases remain unchanged');
const pages=['../index.html','../elegia-breve/index.html','../ojos/index.html','../sonrisa/index.html','../estrella/index.html','../epilogo/index.html','index.html'];
for(const f of pages){const s=fs.readFileSync(path.join(__dirname,f),'utf8');assert(s.includes('narrative-universe.js?v=20261010-23'),`${f} points to shared module version 22`)}
console.log('PASS: 32-scene convergence, completion gate, automatic return, checklist, and one-tap reading start');
